### ISSUE TITLE
cptSetup_bas - ThisProject code gets duplicated on cptSetup()

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#10]
## Problem
cptSetup() duplicates cpt-related lines in ThisProject.

## Solution
Not sure. Troubleshoot.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] create topic branch
- [x] design, code and test
- [x] **rev the codemodule**
- [x] **reset BLN\_TRAP\_ERRORS**
- [x] update CurrentVersions.xml
- [ ] merge and push to develop and/or master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
Separating the previous issue #10 into two, and updating the original issue comment to adhere to issue template.

Duplication was happening due to a wrong argument in .Find(). Replaced this line:

```visual-basic
If cmThisProject.Find("<cpt_version>", 1, 1, cmThisProject.CountOfLines, 1000, True, True) = True Then
```
to this:
```visual-basic
If cmThisProject.Find("<cpt_version>", 1, 1, cmThisProject.CountOfLines, 1000, False, True) = True Then
```

Merged into develop and master for release 1.2.2.
