### ISSUE TITLE
cptStatusSheet - account for users without Outlook

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#102]
## Problem:
References not set to Outlook when it's not installed, so...many errors.

## Solution:
- [x] if no Outlook installed then disable the 'send via email' option
- [x] convert Outlook constants to their numerical values
- [x] also fix the cptCore logic which was quite wrong

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
Released for UAT.
