### ISSUE TITLE
Request: User can export IPMDAR SPD files

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#109]
## Request:

Generate the following exports into a folder in the User's profile directory. Include all necessary data checks. Automatically generate a narrative template with placeholders for needed information (e.g., constraint justifications, leads, lags, CWBS, IMS Data Dictionary, etc.)

- [ ] FileType.txt
- [ ] DatasetMetadata.json
- [ ] SourceSoftwareMetadata.json
- [ ] ProjectScheduleData.json
- [ ] ProjectCustomFieldDefinitions.json
- [ ] ProjectCustomFieldValues.json
- [ ] Calendars.json
- [ ] CalendarWorkshifts.json
- [ ] CalendarExceptions.json
- [ ] Tasks.json
- [ ] TaskScheduleData.json
- [ ] TaskCustomFieldDefinitions.json
- [ ] TaskCustomFieldValues.json
- [ ] TaskConstraints.json
- [ ] TaskRelationships.json
- [ ] TaskOutlineStructure.json
- [ ] Resources.json
- [ ] ResourceCustomFieldDefinitions.json
- [ ] ResourceCustomFieldValues.json
- [ ] ResourceAssignments.json

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
on first run, get the contract name, get sha256 of the contract name, then save *both* in the doc props. when the user reopens the form, prompt to confirm the contract name before proceeding. if doesn't match, then the file has been reused.
