### ISSUE TITLE
Request: use MD5 to verify modules haven't been modified

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#113]
## Request:
Enforce terms of license: if user has modified his modules, replace them (or uninstall).

## Solution:
- [ ] save archival copy on install vs. pull MD5 from the XML
- [ ] run MD5 comparison - see [here](https://stackoverflow.com/questions/2826302/how-to-get-the-md5-hex-hash-for-a-file-using-vba#17858040).
- [ ] replace or remove

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
If user hasn't upgraded, then comparing against the current version's MD5 will be invalid. Yikes. Need to compare against MD5 by version. Which means perhaps a JSON file with version history...?
