### ISSUE TITLE
cptFilterByClipboard - *_frm not recognized as type UserForm

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#125]
## Problem:
Latest `v1.0.5` not recognized as UserForm.

## Solution:
TBD

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
Solution was found [here](https://www.edwardthomson.com/blog/git_for_windows_line_endings.html) and [here](https://docs.github.com/en/enterprise/2.16/user/github/using-git/configuring-git-to-handle-line-endings).
