### ISSUE TITLE
cptStatusSheet - hide before and other logic prollems

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#126]
## Problems:

1. Hide complete before error check should only be `>` not `>=`
```visual-basic
cptStatusSheet_frm.cmdRun():
If CDate(Me.txtHideCompleteBefore.Value) >= CDate(Me.txtStatusDate.Value) Then
```

2. Hide complete before should default to one week prior
```visual-basic
cptStatusSheet.ShowCptStatusSheetFrm():
cptStatusSheet_frm.txtHideCompleteBefore.Value = DateAdd("d", -(Day(dtStatus)-1), dtStatus)
```

## Solutions:
- [x] 1. fix:
```visual-basic
cptStatusSheet_frm.cmdRun():
If CDate(Me.txtHideCompleteBefore.Value) > CDate(Me.txtStatusDate.Value) Then
```
- [x] 2. fix:
```visual-basic
cptStatusSheet.ShowCptStatusSheetFrm():
cptStatusSheet_frm.txtHideCompleteBefore.Value = DateAdd("d", -7, dtStatus)
```

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch
