### ISSUE TITLE
cptCore - potential logic issue with cptSpeed

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#129]
## Problem:
Existing logic may keep Calculation turned off after a macro runs.

```visual-basic
Application.Calculation = pjAutomatic = Not blnOn
```

## Solution

```visual-basic
Application.Calculation = Not blnOn
```

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
This is not an issue. Existing code works as desired.
