### ISSUE TITLE
cptSaveLocal - should we automatically handle formulae? How?

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#131]
## Problem:
When saving down ECFs to LCFs, formulae still reference the ECF name when they need to be updated to reflect the new name.

## Solution
This cannot happen until mapping is complete--perhaps on SaveLocal we can use the mapping in lboMap to replace ECFs with LCFs, and notify the user if the formula relies on an unmapped field?

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Included with Issue #90 in release `v1.6`

**Comment by AronGahagan** [comment]
- [ ] Add Ribbon Button for ECF > LCF
