### ISSUE TITLE
cptResourceDemand_bas - second export gets 'permission denied'

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#14]
## Problem
If the user runs the export twice he gets a 'permission denied' - excel is left open, hidden, in the background:

![Capture](https://user-images.githubusercontent.com/38786138/55276228-b6c76080-52c7-11e9-9612-6773718e58f5.JPG)

## Solution
Add a timestamp to the new filename if a file exists and is open -- follow technique used in [Trace/cptCriticalPathTools_bas.bas](Trace/cptCriticalPathTools_bas.bas):

```visualbasic
  'ensure directory
  strDir = Environ("USERPROFILE") & "\Desktop\"
  If Dir(strDir, vbDirectory) = vbNullString Then MkDir strDir
  'build filename
  strFileName = strDir & Replace(Replace(Project.Name, " ", "-"), ".mpp", "") & "-CriticalPathAnalysis-" & Format(Now, "yyyy-mm-dd") & ".pptx"
  On Error Resume Next
  Set pptExists = pptApp.Presentations(strFileName)
  If BLN_TRAP_ERRORS Then On Error GoTo err_here Else On Error GoTo 0
  If Not pptExists Is Nothing Then 'add timestamp to this file
    pptExists.Save
    pptExists.Close
  End If
  'might exist but be closed
  If Dir(strFileName) <> vbNullString Then
    If MsgBox(strFileName & " exists. Overwrite?", vbExclamation + vbYesNo, "File Exists") = vbYes Then
      Kill strFileName
    Else
      MsgBox "The presentation you are creating will have a time stamp in the filename to prevent overwriting.", vbInformation + vbOKOnly, "File Name Changed"
      strFileName = Replace(strFileName, ".mpp", "-" & Format(Now, "hh-nn-ss") & ".mpp")
    End If
  Else
```

## Todo:
- [x] open an issue branch to fix using git-flow
- [x] build and test the fix
- [x] **rev the module**
- [x] merge hotfix into master and develop using git-flow

**Comment by AronGahagan** [comment]
Took a different approach to checking if the file exists and is open in another instance of Excel -- since if there are multiple instances of Excel, we can't (easily) pick the one with the file open. Instead I simply tried to delete the file if it exists; if the delete failed then I rename it and notify the user.
