### ISSUE TITLE
Upgrade ResetAll feature to include user options

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#140]
## Request:
- [x] Update the Reset All feature to allow for user-saved options like expand all tasks, hide inactive, show summaries, indent name, etc.
- [x] revise the Reset All button to be a splitButton, menu option is the settings page
- [x] clicking the button applies the saved settings
- [ ] WrapItUp defaults to saved OutlineLevel setting or, if not exists, then level 2

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch
