### ISSUE TITLE
cptDynamicFilter - include RegEx and wildcards

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#146]
## Request:
- [x] Include option for RegEx pattern matching; if option is selected then dump UID + Search Field to adtg then either use autofilter or .cptDynamicFilter - do either have limits? Alternatively, cycle through and mark each and use Marked filter
- [x] Include option for use of wildcard (*) to match one or more characters (if wildcard is last character then functionally inert)

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
- [ ] requires new reference set to `Microsoft VBScript Regular Expressions 5.5` -- how to handle that? Update to the Upgrade form is automated; bake in a cptSetReference() in the upgrade form itself, so it fires before the upgrade of the DynamicFilter upgrade? Need to recall how I'd planned to make use of the `cptPatch_bas` module.
- [ ] need warning about overwrite of the `Marked` field, or an automated selection of a free flag, or an alternate method for filtering

**Comment by AronGahagan** [comment]
- [ ] convert settings to `.ini` and use the API version.

**Comment by AronGahagan** [comment]
- [ ] use the 'borrow unused flag' (fallback to text, number); indicate on label
- [ ] shrink the `go` button and add a `?` button with screen tip, then prompt to open a good RegEx site (RegExPal?)

**Comment by AronGahagan** [comment]
Auto-selection, or user-selection, of a Custom Flag Field or Marked field is deferred.
