### ISSUE TITLE
cptStatusSheet_(bas|frm) - 'Index out of range'

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#16]
## Problem
![Capture1](https://user-images.githubusercontent.com/38786138/55276500-8df49a80-52ca-11e9-825b-b5549171573f.JPG)

![image](https://user-images.githubusercontent.com/38786138/55276816-87682200-52ce-11e9-8003-cf79883e9255.png)

Code trips on line 515:

```visual-basic
  cptStatusSheet_frm.lblStatus = " Formatting rows..."
  t = GetTickCount
  'format rows
  'format summary tasks
  Set rSummaryTasks = xlCells(aSummaries(0), 1).Resize(, aHeaders.count)
  For vCol = 1 To aSummaries.count - 1
515:    Set rSummaryTasks = xlApp.Union(rSummaryTasks, xlCells(aSummaries(vCol), 1).Resize(, aHeaders.count))
  Next vCol
  If Not rSummaryTasks Is Nothing Then
    rSummaryTasks.Interior.ThemeColor = xlThemeColorDark1
    rSummaryTasks.Interior.TintAndShade = -0.149998474074526
    rSummaryTasks.Font.Bold = True
  End If
```

Code errors out on Scott's file whether he has summary tasks or not.

## Solution
_I need more information from Scott Fish before I can address this._

## Todo
- [x] Scott Fish to send test file
- [x] Aron to reproduce the error
- [x] create hotfix branch 'issue-16' using git-flow
- [x] build and test
- [x] **rev the module**
- [x] merge

**Comment by AronGahagan** [comment]
The first error from cptStatusSheet_bas was due to the aSummaries, aMilestones, aNormal, and aAssignments SortedArrays being empty--code did not account for this previously, now it does.

The second error, originating in cptStatusSheet_frm, was the same error. The button on the _frm calls the long subroutine in the _bas. When the _bas errors out, so does the form. 

I also removed the 'Man, that's a lot of tasks, are you sure?' prompt I'd accidentally left in there. 💯
