### ISSUE TITLE
cptStatusSheet - improvements

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#162]
## Improvements:
Create Status Sheet:
- [x] restrict data entry; text > comments
- [x] sheet protection, but allow resize columns?
- [x] resize task name column to fixed width and wrap text
- [x] if user selects the cboItems with the keyboard, the AutoFilter event doesn't fire
- [x] user can set base directory
- [x] user can set file naming convention
- [x] user can set email subject
- [x] user can define cc
- [x] user can choose QuickPart
- [x] prompt if tasks exist with blank [item]

Import Status Sheet:
- [x] only import changed ETC; allow import to DURATION fields instead for filter?
- [x] After Import Completes, apply the comparison view and include Task Type immediately to the left of ETC vs. New ETC
- [x] only import changed EV
- [x] recreate and apply ".STATUS SHEET IMPORT FILTER" where {fields} are not empty
- [x] recreate and apply ".STATUS SHEET IMPORT TABLE" below

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
- [ ] require use of [item] on for each worksheet/workbook
- [ ] fields should not be case sensitive

**Comment by AronGahagan** [comment]
Includes fixes to:
#60 - speed up status sheet creation
#115 - account for non-resource-loaded
#120 - include field selections in 'report'?
#121 - apply table and filter after import, say 'complete' in label
#161 - process hangs on fore each row deletion
#176 - remove GUID 
#177 - for loop not initialized (project has no tasks)
#193 - Project Standard has no 'Active' field accessible via the UI
