### ISSUE TITLE
cptResourceDemand - Incorporate Exceptions and Fiscal Calendar

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#165]
## Requests:
- [x] Export Holidays/Exceptions from Project Calendar
- [x] Point FTE_WEEK to holiday exceptions
- [x] Point FTE_MONTH to holiday exceptions
- [x] Point FTE_BL_WEEK to holiday exceptions
- [x] Point FTE_BL_MONTH to holiday exceptions
- [x] Include User Note to use FTE_MONTH if grouping by month
- [x] Use cptFiscalCalendar if Exists; Otherwise prompt to create it
- [x] Setup a Fiscal Month Lookup: WE,YEARMO,HOURS
- [x] Add Option on Worksheet to point FTE_MONTH to FISCAL; Indicate "CALENDAR MONTHS" vs "FISCAL PERIODS" on Table and Chart
- [x] Add Conditional Formatting to Table
- [x] handle when fiscal periods are not 4/4/5 (ending on Friday); if not on a 4/4/5 then perhaps export _daily data_ first to ADODB then summarize SourceData by Fiscal Month (and skip Weeks)?

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
- [ ] When using `NETWORKDAYS()`, take prior fisc_end+1 as start date.
- [ ] Discrepancy between Peak Units and returned FTE is likely an efficiency factor applied to the Max Units available. E.g., if 1 FTE = 80% Max Units available, need to somehow account for that in the FTE_FISCALMONTH calculation. But, how?
