### ISSUE TITLE
cptStatusSheet_frm - disable the 'for each' options

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#17]
## Problem
Shouldn't be enabled if functionality isn't released yet.

## Solution
Disable it.

## Todo:
- [ ] create hotfix branch to fix using git flow
- [ ] fix and test
- [ ] **rev the module**
- [ ] merge and release using git flow
