### ISSUE TITLE
Convert Project GUID in all adtg files to user-defined ProjectName

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#176]
## Problem:
Copying an offline *.mpp file assigns a new GUID so old data is effectively 'lost'.

## Solution:
Prompt user for a project name with a combo box/add button in the following modules:

~Core/cptCommonFieldMap_bas.bas~
- [x] CustomFields/cptDataDictionary_bas.bas
- [x] CustomFields/cptDataDictionary_frm.frm
- [x] Status/cptStatusSheetImport_bas.bas
- [x] Trace/cptSaveMarked_bas.bas
- [x] provide a way for a user to 'recover' lost data - create a workbook to review the data, update the ProjectName field, and re-import

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
`Status/cptStatusSheetImport_bas.bas` will be included in #162 .
