### ISSUE TITLE
Alphabetize CurrentVersions.xml to avoid merge conflicts

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#18]
## Problem
Too many merge conflicts caused by CurrentVersions.xml being non-alphabetized.

## Solution
Alphabetize the creation using a SortedList.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule
- [x] create branch using git flow
- [x] design, code and test
- [x] **rev the codemodule**
- [x] merge and push to master

**Comment by AronGahagan** [comment]
Alphabetized.
