### ISSUE TITLE
OutlineShowAllTasks fails if Sort (no retained outline structure) is applied

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#180]
## Problem:
If a sort is applied, without 'retain outline structure' checked, fails.

## Solution:
Reapply the `Sort` prior to running `OutlineShowAllTasks` 

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Modules to update:

- [ ] Core/cptCore_bas.bas
- [ ] Core/cptResetAll_frm.frm
- [ ] CustomFields/cptSaveLocal_bas.bas
- [ ] Metrics/cptMetrics_bas.bas
- [ ] ResourceDemand/cptResourceDemand_bas.bas
- [ ] Status/cptStatusSheet_bas.bas
- [ ] Text/cptDynamicFilter_bas.bas
- [ ] Text/cptFilterByClipboard_bas.bas
- [ ] Text/cptFilterByClipboard_frm.frm
- [ ] Trace/cptNetworkBrowser_bas.bas
- [ ] Trace/cptNetworkBrowser_frm.frm
- [ ] cptSetup_bas.bas
