### ISSUE TITLE
Request: import export all application settings

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#183]
## Request:
User RK suggested the following:
- [ ] save/export/import all application-level settings to an .ini
- [ ] needs a form for export/import
- [ ] grab every single setting from the Options dialogs

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch
