### ISSUE TITLE
cptSetup_bas - duplicate modules on second run of cptSetup()

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#19]
## Problem
Title says it all.
Also, clear the Application.StatusBar on exit.

## Solution
Try a pause. DoEvents. Otherwise use Sleep.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] create topic branch
- [x] design, code and test
- [x] **rev the codemodule**
- [x] **reset BLN\_TRAP\_ERRORS**
- [x] update CurrentVersions.xml
- [x] merge and push to develop and/or master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
DoEvents appears to have done the trick - nice call, @ryanbeard82 . Issue closed.

**Comment by AronGahagan** [comment]
The DoEvents is not working on my machine. Reopening issue.

**Comment by AronGahagan** [comment]
Implemented a new method of removing modules at runtime:
```visual-basic
 '<issue19>
Set vbComponent = ThisProject.VBProject.VBComponents(strModule)
vbComponent.Name = vbComponent.Name & "_" & Format(Now, "hhnnss")
DoEvents
ThisProject.VBProject.VBComponents.remove vbComponent
DoEvents '</issue19>
...
Set vbComponent = Nothing
```

...appears to be working.
