### ISSUE TITLE
cptMetrics: SPI does not properly account for unstarted LOE tasks with BCWS in the past

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#192]
## Problem:
If an LOE tasks is 'unstarted' and gets pushed out, it's Physical % Complete will be likely be zero. But it's BCWP should equal its BCWS despite it's having not started yet. This results in an understated BCWP, thus an understated SPI.

## Solution:

- [x] provide a way for the user to identify LOE tasks
- [x] account for LOE the same way as in the KEO SPI tool instead

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch
