### ISSUE TITLE
Project Standard has no 'Active' field accessible via the UI

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#193]
## Problem:
The Property `Task.Active` exists but is not accessible via the UI in Project Standard. So: cannot be added to a table, used in a filter (?), group, or autofilter.

## Solution:
Use `Application.Edition` to make determination. The following modules (# instances) need revision:

- [x] Core/cptCore_bas.bas:1
- [x] Core/cptResetAll_frm.frm:2
- [x] Count/cptCountTasks_bas.bas:2
- [x] Integration/cptIMSCobraExport_bas.bas:18
- [x] Metrics/cptGraphics_bas.bas:1
- [x] Metrics/cptMetrics_bas.bas:3
- [x] ResourceDemand/cptResourceDemand_bas.bas:1
- [x] Status/cptStatusSheetImport_bas.bas:1
- [x] Status/cptStatusSheet_bas.bas:2
- [x] Status/cptStatusSheet_frm.frm:1
- [x] Text/cptText_bas.bas:3
- [x] Trace/cptNetworkBrowser_bas.bas:4

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
Stop the presses. The property `Task.Active` exists, but the field named `Active` (and thus any AutoFilters or Filters applied to it) is inaccessible via the UI in Project Standard. 

Back to the drawing board.

**Comment by AronGahagan** [comment]
Pushed branch for user WW to test out.

**Comment by AronGahagan** [comment]
Included in #162
