### ISSUE TITLE
Path to Desktop not Found when user is syncing to OneDrive

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#194]
## Problem:
When a user is syncing his Desktop with OneDrive, `Environ("USERPROFILE") & "\Desktop\"` returns a `PATH NOT FOUND` error.

## Solution:
Convert all instances of the above to `CreateObject("WScript.Shell").SpecialFolders("Desktop")`

- [x] cptResourceDemand_bas
- [x] cptText_bas
- [x] cptCriticalPathTools_bas

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Possibly create a common function `cptGetUserDesktop` and put it into the cptCommon_bas module.
