### ISSUE TITLE
cptStatusSheet - Conditional Formatting

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#195]
## Feature Request:

- User can (optionally) enable conditional formatting to the Status Sheet to assist CAMs in data entry.
- Import kicks out email per workbook with list of invalid entries and attaches filtered file for 2nd round

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
Includes improved Data Validation on EV% - must be between 0 and 1 (read: 0% and 100%).

**Comment by AronGahagan** [comment]
test run on QuadCopter master/sub.
fixes needed:
### cptIntegration_frm:
- [ ] also need cboEVT (in cptStatusSheet_bas)
- [ ] ECFs not available...? (logic? process?)
- [ ] "Physical % Complete" failing
- [ ] if chkSyncCOBRA then confirm setting actually exists
### cptStatusSheet_bas:
- [ ] update settings as soon as user changes them - each control
- [ ] need more room on CF pick list
- [ ] if user doesn't make a selection, setting doesn't exist, so fails on next form open
- [ ] catch how user closes form: if done, save; if cancel (X) then don't
- [ ] update settings on cmdDone
- [ ] required shading didn't work if Conditional Formatting isn't checked
- [ ] "UID not found" >> cptGetAssignmentData is overwriting cells
- [ ] when finding a task, if 'ignore LOE' is checked, do you still look for it?
- [ ] add a "Complete" MsgBox
- [ ] if Task Usage has a default Group...?
### cptTaskHistory_bas:
- [ ] cptTaskHistory_bas: change all CInt >> CLng : 
- [ ] cptTaskHistory_bas: add a prompt that export is done
