### ISSUE TITLE
cptStatusSheet & cptStatusSheetImport - Prevent Note Duplication

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#197]
## Problem:
If a user selects `Export Notes` when creating the Status Sheet, then selects `Import Notes: Append to [Top|Bottom]` - the Note will be doubled up.

## Potential Solutions:

- [ ] Only allow a Import-Replace option
- [ ] Maintain a Task Notes Journal in adtg
- [ ] Allow the CAM to decide whether to add / replace
- [ ] Show Task/Assignment Notes as a comment popup on the Task Name column, new notes would be added to the Reason / Action / Impact column the current options to Append to Top or Bottom need no changes

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
Solution: Only enable this option if the user has run `Capture Week` for the current week, and import notes to `Task History` instead of the Task Note. Provide options to export all history for a given task, for a given project, or for a given status date.

**Comment by AronGahagan** [comment]
Provide an option with `Create Status Sheet` to export the Task Note as a Comment on the Task Name cell; as well as an option to include `X` weeks of Task History as a comment on the Reason / Action / Impact cell.

**Comment by AronGahagan** [comment]
...allow Assignment-level History? ...remove option to 'Allow Assignment-Level Notes'?
