### ISSUE TITLE
Make BLN_TRAP_ERRORS a function that reads an .ini setting instead of a Private Constant

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#199]
## Request:
Make `BLN_TRAP_ERRORS` a Function that reads a setting in the .ini file instead of a hard-coded Private Constant.
Put a `mode=debug | run` toggle on `cptSettings_frm`

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
## Update Strategy:
- [ ] Keep `Private Const BLN_TRAP_ERRORS` in existing modules intact
- [ ] Add `Boolean BLN_TRAP_ERRORS As Boolean` and `BLN_TRAP_ERRORS = CBool(cptGetSetting("General","ErrorTrapping"))` to updated modules and remove `Private Const BLN_TRAP_ERRORS` - default to `TRUE`
- [ ] This way, if user does not update _all_ modules, the original `Private Const` will still work correctly, while updated modules will use the new method
- [ ] handle case when Feature `General` and Setting `ErrorTrapping` does not exist

**Comment by AronGahagan** [comment]
Merged to `develop` in prep for next minor release.
