### ISSUE TITLE
cptMetrics - Earned Schedule - older versions of Excel do not support MAXIFS()

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#203]
## Problem:
`MAXIFS()` not supported prior to Office 2019/365.

## Potential Solutions:

- [x] `=MAX(--(B1:B160>0)*(A1:A160))`

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Sent to client for testing.
