### ISSUE TITLE
Request: cptStatusSheet - Network Drive compatibility

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#205]
## Request:
User can save to/import from a Network Drive. I don't know that I have a way to test this...

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
The `Dir([path], vbDirectory)` method actually works in identifying whether a network path exists, so the issue is something else...
