### ISSUE TITLE
Request: User can keep Smart Duration form open

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#213]
## Request:
User can 'keep open' the Smart Duration form.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
- [ ] improve test for elapsed duration. `Instr(t.DurationText,"e")` yields false positives on minute/s, year/s, and week/s. Use `Left(cptRegex(t.DurationText,"[A-z]{1,}"),1) = "e"`
