### ISSUE TITLE
cptStatusSheetImport - if columns are hidden or sorted then import fails

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#214]
## Problem:
User will receive `Error 91: Object Variable or With block variable not set` if Status Sheet has hidden columns or sorts applied.

## Solution:
- [x] unhide all columns on worksheet open (close without saving)
- [x] do not allow sorting in protection (then should sheet protection be enabled by default)?

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch
