### ISSUE TITLE
cptStatusSheet - do not set chkAllItems = True if cboCreate = 0

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#215]
## Problem:
User WW reports error on form start up. 
Issue: with saved settings of `StatusSheet.cboCreate=0` and `StatusSheet.chkAllItems=1` and even `StatusSheet.cboEach=Team` - since cboEach.Change() does not fire, there are no items in lboItems to build a non-zero-length string.

## Solution:
- [x] Prevent setting chkAllItems to True if cboCreate = 0
- [x] Handle when lboItems has ListCount=0 after setting chkAllItems=1 -- IsNull() is not enough

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch
