### ISSUE TITLE
cptSetup & cptUpgrade - toggle new project to reset ribbon

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#23]
## Problem
After running cptSetup() or Upgrading, the toolbar looks like nothing has happened. It should update so the user knows that _something happened_.

## Solution
Need to trigger Project_Activate.
- [ ] Try: turn off screenupdating, add a new project, close the new project, activate currentproject

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] create topic branch
- [x] design, code and test
- [x] **rev the codemodule**
- [x] **reset BLN\_TRAP\_ERRORS**
- [x] update CurrentVersions.xml
- [x] merge and push to develop and/or master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Too many complications and errors trying to refresh after cptSetup - has to do with the clsEvents module I believe. But the cptUpgrades one works after a minor screen flicker. I think the flicker is better than nothing happening but open to other opinions.
