### ISSUE TITLE
git - resolve whitespace LF/CRLF issues

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#24]
**Describe the bug**
Whitespace is added to modules on import/export in git.

**To Reproduce**
use gitVBA

**Expected behavior**
There should not be any whitespace.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
This has nothing to do with git or its autocrlf settings. This happens on native export from/import to the VBE, so it will have to be managed via VBA code.

**Comment by AronGahagan** [comment]
Directly after importing a module, run the following to clear out the whitespace added at the top of the VbComponent's CodeModule:

```visual-basic
'remove the whitespace added by VBE import/export
With ThisProject.VBProject.VBComponents(strModule).CodeModule
    For lngLine = .CountOfDeclarationLines To 1 Step -1
        If Len(.Lines(lngLine, 1)) = 0 Then .DeleteLines lngLine, 1
    Next lngLine
End With
```

This is needed in both `cptSetup_bas.cptSetup()` and `cptUpgrades_frm.cptUpgradeSelected()`.

**Comment by AronGahagan** [comment]
Also needed in `cptCore_bas`. Done.
