### ISSUE TITLE
cptMarked - show all tasks before applying saved set

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#244]
## Problem:
If outline is collapsed, applying appears not to work (as summary tasks are hidden on filter).

## Solution:
```vba
'ensure task pane is active
SelectAll
OutlineShowAllTasks
```

Also: improve this by adding two options to the form: 
- [x] filter on apply
- [x] hide/show summaries
- [x] use `FilterEdit`

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
