### ISSUE TITLE
cptUpgrade_frm - upgrade of ThisProject needs refinement

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#25]
## Problem
Upgrade of `ThisProject` fails.

## Solution
Similar to [cptSetup()](../blob/5fadf662c9aec885eb9238767bb2faa646a19656/cptSetup_bas.bas#L14) we need to catch the `ThisProject` module upgrade and handle it line-by-line.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
## Discovered: One More Way Not To Do It
This is painful...the following line trips an error:

```visual-basic
    'clear out existing lines of cpt-related code
    Set cmThisProject = ThisProject.VBProject.VBComponents("ThisProject").CodeModule
    For lngLine = cmThisProject.CountOfLines To 1 Step -1
      'cover both '</cpt_version> and '</cpt>
      If InStr(cmThisProject.Lines(lngLine, 1), "'</cpt") > 0 Then
'---------------------------------------------------------------
ERROR >>cmThisProject.DeleteLines lngLine, 1<< ERROR
'---------------------------------------------------------------
        DoEvents
      End If
    Next lngLine
```
![image](https://user-images.githubusercontent.com/38786138/55506092-975f6900-5622-11e9-8ca9-fb7d55972631.png)

Hitting **End** stops in the middle of the process; hitting **Continue**... _crashes Project_.

What is frustrating about this is that running the cptSetup() a second time follows a similar process...but does _not_ crash Project. I don't get it. Could it be because the code is running from inside a Form's CodeModule...?

## New Approach
- [ ] try running the code from a regular code module
- [ ] try loading the full code of each procedure into an array, delete _from the array_ the `</cpt` lines (keeping the user's), then try a bulk overwrite of the entire procedure code. I suspect this will trip the same exact error.

**Comment by AronGahagan** [comment]
Previous diagnosis incorrect. The true problem is in this line, from Issue #23:

```visual-basic
  '<issue23> trigger ribbon refresh
  Application.ScreenUpdating = False
  Set Project = ActiveProject
  Projects.Add
  FileCloseEx pjDoNotSave
  Project.Activate '</issue23>
```
I kept the code int the Form's CodeModule and it's working. So why isn't the above code working? Seeping into Issue #23 a bit, I sprinkled a few `DoEvents` statements in that fix and, _lo, and behold_, it works:

```visual-basic
  '<issue23><issue25> trigger ribbon refresh
  Application.ScreenUpdating = False
  Set Project = ActiveProject
  Projects.Add
  DoEvents
  FileCloseEx pjDoNotSave
  DoEvents
  Project.Activate '</issue25></issue23>
```

Now to reset cptSetup(), twice, and Upgrade, etc.

**Comment by AronGahagan** [comment]
This issue has been overcome by events. Discoveries and fixes in Issue #26 have also fixed this issue.
