### ISSUE TITLE
cptNetworkBrowser - tweak for performance

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#250]
## Improvement:

Don't use:
```vba
If oLink.To.Name = oTask.Name Then
```
Instead, use:
```vba
If oLink.To.GUID = oTask.GUID Then
```

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch
