### ISSUE TITLE
Deconflict FileDialog for BAE implementation

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#251]
## Request:
Deconflict `FileDialog` for BAE implementation:
```vba
Dim oFileDialog As FileDialog
Dim FileDialog As FileDialog
```
## Solution
```vba
Dim oFileDialog As Object 'FileDialog
```

## Scope:
- [ ] Backbone/cptBackbone_bas.bas:12
- [ ] Calendar/cptFiscal_bas.bas:3
- [ ] CustomFields/cptSaveLocal_bas.bas:6
- [ ] Status/cptIPMDAR_bas.bas:5
- [ ] Status/cptStatusSheetImport_frm.frm:5
- [ ] Status/cptStatusSheet_frm.frm:4

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch
