### ISSUE TITLE
Request: add [Program] variable to StatusSheet FileName, Email Subject, Email Body

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#256]
## Request
Add `[PROGRAM]` variable to StatusSheet FileName, Email Subject, Email Body.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch

**Comment by AronGahagan** [comment]
- [ ] cptStatusSheet_frm.txtFileName.Change()
- [ ] cptStatusSheet_frm.txtFileName.ToolTipText
- [ ] cptStatusSheet_frm.???.ToolTipText
- [ ] cptStatusSheet_bas - strFileName creation
- [ ] cptStatusSheet_bas - Email Body Find/Replace
