### ISSUE TITLE
modify CurrentVersions.xml structure for ease and efficiency

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#257]
## Request:
Modify `CurrentVersions.xml` to simplify and make it easier to interrogate using `vba`.

change:

```xml
        <Module>
                <Name>cptStatusSheet_bas</Name>
                <FileName>cptStatusSheet_bas.bas</FileName>
                <Version>v1.3.2</Version>
                <Type>1</Type>
                <Directory>Status</Directory>
        </Module>

```

to:
```xml
        <Module>
                <FileName>Status/cptStatusSheet_bas.bas</FileName>
                <Version>v1.3.2</Version>
        </Module>
```

better format would've been:
```xml
        <Feature>cptStatusSheet</Feature>
                <Module>Status/cptStatusSheet_bas.bas</Module>
                <UserForm>Status/cptStatusSheet_frm.frm</UserForm>
                <Version>v1.3.2</Version>
        </Feature>
```

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
...nah. marked `wontfix`
