### ISSUE TITLE
cptIMSCobraExport_bas - fix datatype 

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#258]
## Problem:

```vba
Integration/cptIMSCobraExport_bas.bas:6345:   tempWork = CDbl(tsv.Value) - CLng(tsva.Value)
Integration/cptIMSCobraExport_bas.bas:6435:   tempWork = CDbl(tsv.Value) - CLng(tsva.Value)
Integration/cptIMSCobraExport_bas.bas:6525:   tempWork = CDbl(tsv.Value) - CLng(tsva.Value)
```

## Solution
```vba
Integration/cptIMSCobraExport_bas.bas:6345:   tempWork = CDbl(tsv.Value) - CDbl(tsva.Value)
Integration/cptIMSCobraExport_bas.bas:6435:   tempWork = CDbl(tsv.Value) - CDbl(tsva.Value)
Integration/cptIMSCobraExport_bas.bas:6525:   tempWork = CDbl(tsv.Value) - CDbl(tsva.Value)
```

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch
