### ISSUE TITLE
cptSetup_bas - add cptUninstall()

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#26]
## Problem
Need a way for users to refresh their installation, or drop it when leaving a client if desired. Will be helpful also for us supporting the tool - a one-click way to reset without having to direct the user to the Organizer or to the ThisProject code module in the VBE.

## Solution
The subprocedure should:
- [x] clear out cpt-related lines from the ThisProject module (including the version)
- [x] remove all cpt* modules (except cptSetup) - perhaps saving them to `c:\[users]\cpt-backup\modules` just to be safe
- [x] comment out all other lines in the Project_Activate event to avoid immediate errors - and notify user
- [x] trigger a refresh of the Project_Activate subprocedure to remove the toolbar

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
This tale grew in the telling...

In course of putting adding the cptUninstall script, I ran into a few issues and stumbled on to a massive improvement in the way the ribbon gets refreshed. So I went ahead an implemented it throughout: in cptSetup(), in cptUpgrades_frm, and there were impacts to cptCore_bas().

Now the ribbon refreshes on install, on uninstall, and on upgrade, without losing focus. 💯
