### ISSUE TITLE
Request: user can explore task history

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#260]
## Request:
- [x] User can explore task history (from existing CEI data)
- [ ] ~Add ETC to dataset (array of assignments?)~ [ too complicated for a v1.0.0 ]
- [ ] ~Add EV% to dataset~ [ canceled ]
- [x] Updates on selection change
- [x] Start, Finish (actuals in brackets)
- [x] calculated (overall) duration
- [x] sorted by status date desc
- [ ] ~Restore button?~ [ canceled ]
- [x] Asterisk on Status Date if STATUS NOTE exists
- [ ] ~The Blame Report based on CEI data vs Custom Fields~ [ deferred ]
- [x] Helper function to test for a field and add it if not exists

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch

**Comment by AronGahagan** [comment]
- [ ] user can optionally export: all history for selected task; all tasks in current period (optional: with notes only)
