### ISSUE TITLE
cptFilterByClipboard - glitch when no available number fields

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#263]
## Problem:
If no fields are available, an error occurs.

```vba
Text/cptFilterByClipboard_bas.bas:365:  rstFree.MoveFirst
Text/cptFilterByClipboard_bas.bas:378:  rstFree.MoveFirst
```

## Solution:
```vba
Text/cptFilterByClipboard_bas.bas:365:  If Not rstFree.EOF Then rstFree.MoveFirst
Text/cptFilterByClipboard_bas.bas:378:  If Not rstFree.EOF Then rstFree.MoveFirst
```

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Flawed logic in v1.8.8!
- [ ] first get array of unnamed custom task number fields > if not exist, then `none available`
- [ ] then remove if task data exists > if all unnamed custom task number fields have task data > `none available`
