### ISSUE TITLE
cptFilterByClipboard - improve UI for typed-in values

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#264]
## Problem:
When user types in a list of UIDs the filter triggers at first key press and user cannot type any more.

## Solution:
- [ ] do not trigger the filter unless user types a `,`
- [ ] do not trigger the switch to lbo unless the user types a `vbCrLf` or has pasted an array
- [ ] work through potential impact to `cptClipboardJump` - only do the jump if the lbo is active

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
Too many conflicts catching pasted data. User can already paste a data list or a comma-separated list of UIDs. Not value-added to also enable manual hand-jammed comma-separated list.
