### ISSUE TITLE
allow install to Enterprise for testing purposes

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#266]
## Problem:
User cannot install to Enterprise Project Global. Allow, but for testing purposes.

```vba
cptSetup_bas.bas:52:  If InStr(ThisProject.FullName, "Global.MPT") = 0 Then
```

## Solution:
- [x]  Global (+ non-cached Enterprise)
- [x] Checked-out Enterprise Global
- [x] `Global.MPT` > `Global`

```vba
cptSetup_bas.bas:52:  If InStr(ThisProject.FullName, "Global") = 0 Then
```

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
