### ISSUE TITLE
cptText_bas - multiple tweaks

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#268]
## Tweaks:

- [x] fix error trapping;
- [x] handle when file is already open;
- [x] make backwards compatible, change `.SortFields.Add2` to `.SortFields.Add`

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
