### ISSUE TITLE
cptEvents_cls - fix gap in logic on a fresh install

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#271]
## Problem:
On a fresh install, `cptCountTasks_bas` doesn't exist yet so `cptGetShowStatusBarCount()` errors out.

## Solution:
- [x] can the function live right in cptEvents_cls? ...should it?

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
