### ISSUE TITLE
Excel 2016 Compatibility

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#273]
## Problems:
The following are incompatible with earlier versions of Excel:
- [x] `SortFields.Add2` change to `SortFields.Add` in `cptAgeDates_bas` and `cptMetrics_bas`
- [x] Remove `.Address` property from all `oListObject.Add()` methods in `cptMetrics_bas` and `cptResourceDemand_bas`

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch

**Comment by AronGahagan** [comment]
- [ ] also replace `Add2` and `Formula2` and `Formula2R1c1`
- [ ] use contribution from David Mendoza

**Comment by AronGahagan** [comment]
- [ ] Use `=LOOKUP(MIN(IF(FISCAL[fisc_end]>=J2,FISCAL[fisc_end])),FISCAL[fisc_end],FISCAL[label])` but it must be entered as an Array Formula for users of Excel 2016. How to determine?
