### ISSUE TITLE
cptMetrics - update CEI for newer NDIA formula

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#275]
## Update:
- [ ] exclude LOE from the calculation - NDIA 2019 PASEG instructs to exclude LOE; whereas NDIA 2014 Predictive Measures Guide instructs to include it. Go with 2019 because 1: more recent and 2: makes more sense.
- [ ] fix title glitch on 'next week' list

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch
