### ISSUE TITLE
Feature Request: Create Outline Code from Task Outline

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#28]
## Feature Request
- [x] User can create Outline Codes from Task Summary Outline.
- [ ] works with master/subprojects.

## Todo:
- [x] assign this request
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch
