### ISSUE TITLE
Request: user can track and manage QBDs

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#284]
## Request:

User can track and manage QBDs. Feature must:
- [ ] work with a project file whether opened standalone or in master/sub 
- [ ] capture the following data points:
- - [ ] PROGRAM (existing setting 'program acronym')
- - [ ] PROJECT_UID
- - [ ] TASK_UID (if subprojects.count>0 then derive formula)
- - [ ] STEP_NAME (description)
- - [ ] STEP_WEIGHT (any set of numbers, could total 100 but not necessary)
- - [ ] STEP_PERCENT (limited via UserForm to between 0 and 100)
- - [ ] STATUS_DATE 
- [ ] provide a way for user to add, edit, and remove QBDs manually
- [ ] provide a way for user to export/import QBD updates to/from stakeholders via Excel (with add/edit/remove function included)
- [ ] calculate the EV% and update the parent task’s (user selected) EV% field
- [ ] export full dataset by program, include other fields (simple string)

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
If user changes the `Program Acronym` then remember to also prompt to update this dataset.

**Comment by AronGahagan** [comment]
- [ ] use `PF` and `FINISH` instead of `AS` and `AF`

**Comment by AronGahagan** [comment]
- [ ] if user has `cptFiscal` calendar, then enable a query for any fiscal periods within (discrete-only) POP _without_ either a BLF or a STEP_PF.

**Comment by AronGahagan** [comment]
- [ ] keep `oRecordset` open while form is open for better performance
- [ ] remove `lblUID` and use `cptQBD_frm.lngQBDUID` instead

**Comment by AronGahagan** [comment]
- [ ] replace all references to `step` with `action`. 
- [ ] ACTION_UID = TASK_UID.ACTION_ORDER

**Comment by AronGahagan** [comment]
- [ ] if task is baselined and user attempts to change the weight total, prompt for a BCR# field (use COBRA Export field or get new one)

**Comment by AronGahagan** [comment]
could use a locked/unlocked status. no baseline = unlocked. baselined = locked, but can unlock by entering a BCR # which gets added to the action record (concatenated string). flag with valid/invalid status. invalid = weights don't equal 100; PF outside of Task BL POP; AF > Status Date OR AF > Task AF; count of actions =1; _at least 1 action per fiscal period?_

**Comment by AronGahagan** [comment]
concerned about the project renaming function. if a previous file is used as basis of a new file, new file would retain the DocumentProperty. If it gets renamed, past records would get overridden. do we need to prompt to confirm Program Acronym _each time_ it's used? that's horrible
