### ISSUE TITLE
Request: user can import/export Cost Rate Tables

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#287]
## Request:
User can import/export Cost Rate Tables.

- [x] optionally, allow addition of non-existent resources
- [x] optionally, flag resources added, updated, not updated

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch

**Comment by AronGahagan** [comment]
- [ ] if possible, add button to a ClearPlan group on the Resource tab
