### ISSUE TITLE
Request: user can skip fields on Data Dictionary export

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#289]
## Request:
User can designate custom fields to ignore when creating the Data Dictionary export.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch

**Comment by AronGahagan** [comment]
- [ ] rebuild the `adtg` and include boolean field `IGNORE` defaults to `0`.
- [ ] update the form / UI
- [ ] update the export to include anything with 1) custom field name OR 2) formula OR 3) a pick list
- [ ] update the export to ignore fields where `IGNORE=1`
