### ISSUE TITLE
Feature Request: User can Export a Data Dictionary

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#29]
## Feature Request
User can export all local and enterprise custom fields (and all available attributes) into an Excel document.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Complete for local custom fields; need to add enterprise custom fields.

**Comment by AronGahagan** [comment]
Complete for enterprise custom fields, but need to account for master/subprojects when there is a discrepancy.

**Comment by AronGahagan** [comment]
I'm thinking we should create a form to capture the field descriptions, and save them locally. When the user elects to export the Data Dictionary he would be presented with a form where he could optionally make updates to the descriptions. This would prevent having to re-run it and copy/paste from the previous version of the Data Dictionary, which is especially onerous during the frantic pre-IBR period.

Drawback would be that it couldn't easily be shared, though we figure that out:
- post *.adtg file to a shared directory (best option)
- export/import descriptions
- create a function to do a mass export of all local custom fields from project to the other?

It would need to allow for multiple projects - perhaps use `ActiveProject.GetServerProjectGuid` - *but does MS Project Standard populate this value?*

---
Went ahead and did it...

![image](https://user-images.githubusercontent.com/38786138/56246717-c3daa280-6070-11e9-86bb-a2a5beb4653c.png)

If the user hits the `Custom Fields...` button while the form is open, and adds, edits, or deletes Custom Field values, the form refreshes as soon as the user saves his changes, and the selection is returned to the field the user was on beforehand (provided it still exists). Everything is based on the Long Field ID.

---
Perhaps a future enhancement might be to allow re-importing a previous description if it gets lost somehow. We would have to capture the Field ID in a hidden column in the Data Dictionary, and the import would probably only include Field ID and Description...maybe...dunno

**Comment by AronGahagan** [comment]
**todo**: finish the search filter.

**Comment by AronGahagan** [comment]
- [x] Search filter done.
- [x] Listbox results alphabetized.
- [x] aesthetics tightened up a bit.

v1.0 of this feature is ready for testing and eventual merge into branch `release-v1.5` and then into `master` for Coronado release.

_Note: updated all search text boxes (resource demand, status sheet) to wrap search query text in apostrophes to avoid error when user enters a space character in the search bar._

**Comment by AronGahagan** [comment]
This form was not loading properly due to it being read/written in unix format rather than dos.

To fix:
1. open file in vim;
1. use `:setlocal ff=dos` followed by `:w` to write the file;
1. see [this page](https://vim.fandom.com/wiki/File_format) for more information.

**Comment by AronGahagan** [comment]
There are now duplicate values for each custom field; and custom fields are popping up for the wrong project. How to fix this? Insert a custom project field cptDataDictionary and a timestamp?

**Comment by AronGahagan** [comment]
Added import capability.

**Comment by AronGahagan** [comment]
released to test
