### ISSUE TITLE
derive original subproject unique ids

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#290]
## Problem:
The factor applied for inserted subprojects is _not_ tied to `ActiveProject.Subprojects(1).InsertedProjectSummaryTask.UniqueID`. If a subproject is deleted, then re-added, the masked UID reflects a value using previously inserted UID. Subsequent inserted project UIDs are not used to calculate the masked UID.

## Solution:
Unless or until we figure out where that value is stored, create a mapping at runtime of `oTask.Project` and the _original_ factor applied.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Confirm changes in:
- [ ] cptCore_bas
- [ ] cptMetrics_bas
- [ ] cptNetworkBrowser
- [ ] cptFilterByClipboard
