### ISSUE TITLE
add cptViewExists, cptTableExists, and cptGroupExists to cptCore_bas

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#291]
## Request
We have `cptFilterExists`, `cptModuleExists`, `cptCalendarExists`, and `cptReferenceExists` functions. Also add:

- [x] cptViewExists
- [x] cptTableExists
- [x] cptGroupExists

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
