### ISSUE TITLE
Request: Better Milestones Pro Refresh Report

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#294]
## Request:
Incorporate a better refresh report for Milestones Pro.

- [ ] input: Milestones Pro refresh report saved as a `txt` file
- [ ] output: nice-looking DELTA report in Excel
- [ ] feature goes in the After Status Group

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch
