### ISSUE TITLE
cptCore_bas - cptAbout_frm will not launch

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#30]
## Problem
Title says it all. Evidently Issue #19 did not fix this portion of the problem (though I could swear it was working before). I was attempting to set a reference to a form indirectly to avoid tripping an error if it didn't exist.

```visual-basic
  Set frmAbout = cptGetUserForm("cptAbout_frm") '<issue19>
...
  For Each UserForm In VBA.UserForms
    If UserForm.Name = strModuleName Then
      Set cptGetUserForm = UserForm
      Exit For
    End If
  Next
```
I believe the **larger issue** is that all of a sudden the VBA.UserForms thingy is returning a zero count.

## Solution
Toss computer out window, take up farming.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
The `VBA.UserForms` collection is only populated with _loaded_ forms. So there's _that_. I've reverted the code back to simply calling `cptAbout_frm` and will just risk it. The cptAbout_frm is firing again, so, issue closed. No rev on this one.
