### ISSUE TITLE
cptStatusSheet - reset selection and delete Sheet1

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#302]
## Problem:
- [ ] Sheet1 still exists...
- [ ] EVT lookup is selected by default

## Solution:
- [ ] Delete Sheet1
- [ ] Reset each worksheet selection to status date

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch
