### ISSUE TITLE
cptStatusSheet - set default date format before creating sheets and restore after

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#305]
## Problem:
Some date formats don't get recognized as Date data type in Excel upon import.

## Solution:
- [x] capture user's `DefaultDateFormat` upon form open
- [x] set to pjMMDDYY for sheet creation
- [x] reset user preference after run, on form close, or on error

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
