### ISSUE TITLE
make Task and Tasks objects Explicit

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#307]
## Problem:

```vba
Dim oTask As Task
Dim oTasks As Tasks
ByRef oTask As Task
ByRef oTasks As Tasks
```

## Solution:

```vba
Dim oTask As MSProject.Task
Dim oTasks As MSProject.Tasks
ByRef oTask As MSProject.Task
ByRef oTasks As MSProject.Tasks
```

Modules:
- [x] Backbone/cptBackbone_bas.bas:5
- [x] Count/cptCountTasks_bas.bas:1
- [x] Core/cptCore_bas.bas:1
- [x] CustomFields/cptSaveLocal_bas.bas:4
- [x] Metrics/cptMetrics_bas.bas:12
- [x] ResourceDemand/cptResourceDemand_bas.bas:1
- [x] Status/cptAgeDates_bas.bas:2
- [x] Status/cptStatusSheetImport_bas.bas:1
- [x] Status/cptStatusSheet_bas.bas:6
- [x] Status/cptStatusSheet_frm.frm:1
- [x] Text/cptDynamicFilter_bas.bas:1
- [x] Text/cptDynamicFilter_frm.frm:2
- [x] Text/cptFilterByClipboard_bas.bas:3
- [x] Text/cptFilterByClipboard_frm.frm:2
- [x] Text/cptText_bas.bas:7
- [x] Text/cptText_frm.frm:1
- [x] Trace/cptCriticalPathTools_bas.bas:3
- [x] Trace/cptNetworkBrowser_bas.bas:5
- [x] Trace/cptNetworkBrowser_frm.frm:3
- [x] Trace/cptSaveMarked_frm.frm:2

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
