### ISSUE TITLE
cptUpgrades_frm - form cannot upgrade itself

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#31]
## Problem
Obviously, the form cannot upgrade itself. When it tries, it doesn't merely _fail_, it takes its world down with it, crashing Project and corrupting the Global.MPT file. #badjuju

## Solution
Do not even show cptUpgrades_frm in the upgrade list. Automatically upgrade it in the background of cptSetup() before showing it.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
**Solution**: when the user opens the Upgrade Form, the form itself is automagically upgraded and the user is prompted accordingly, and asked to re-open. This is not ideal, but the file removal is causing a state loss (which, strangely, doesn't happen during the uninstall, the setup, or upgrades), and this was the only workaround I could come up with. Any ideas, @ryanbeard82 ?

**Comment by AronGahagan** [comment]
Issue #31 _**cracked**_ - my habit for years has been to open UserForms non-modally so the user can continue working "off-form" if desired. Opening the form modally not only _avoids state loss_, but also avoids the annoying prompt to ask the user to re-open the update form.

The fix was as simple as changing this:
```visual-basic
cptCore_bas (584): cptUpgrades_frm.Show False
```
...to this:
```visual-basic
cptCore_bas (584): cptUpgrades_frm.Show
```
`cptUpgrade_frm` now upgrades itself silently in the background and the user is not prompted to re-open. It still appears in its own list of modules, but will never show an update required.

**Closing Actions:**
- [x] bumped the version on `cptSetup_bas` (moved `cptUpgrade()` to `cptCore_bas`);
- [x] bumped the version on `cptCore_bas`;
- [x] updated `CurrentVersions.xml` accordingly;
- [x] merged `issue31` into `develop` and pushed; 
- [x] merged `develop` into `master` and pushed.

**Comment by AronGahagan** [comment]
Just tested `cptUninstall()`, `cptSetup()`, and `cptUpgrades_frm`. 

All clear.
