### ISSUE TITLE
Request: add current period stacked bars to cptLateStartsFinishes SPA Chart and labels

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#310]
## Request
- [ ] add clustered columns for BLF, AF, FF on a secondary axis
- [ ] add data callouts for current period BLF count and AF count
- [ ] make chart bigger

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch
