### ISSUE TITLE
hotfix for Application.Version bug

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#312]
## Problem:
In a recent release, `Application.Version` returns "rmj.rmm" instead of the version number.

## Solution:
Use `CLng(Left(Application.Build,2))` instead.

Affected Modules:
- [x] cptSetup_bas.bas
- [x] cptSaveLocal_bas.bas
- [x] cptSaveLocal_frm.frm

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
