### ISSUE TITLE
Fix FilterByClipboard glitch

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#313]
## Problem:
`cptFilterByClipboard` glitches when user manually types in a comma-separated list of ID/UIDs. Also, the lbo should be cleared on txtFilter_Change, and instances where lbo listcount=0 need to be handled.

## Solution:
Fix the glitch, mimic "enter" behavior with comma, account for when lbo.listcount is 0.

## Todo:
- [x] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch
