### ISSUE TITLE
Request: allow bulk prepend/append on all custom task text fields

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#314]
## Request:
Allow user to operate on all custom task text fields, not just task name.

- [x] how to handle where values are not in a predefined pick-list AND new values cannot be added (this is a read-only setting so may have to just trial-and-error it)
- [x] ~need to limit selection to a single column, and auto-detect which column~
- [x] add a combobox to the form for user to select Target, and update preview accordingly
- [x] ~include TARGET field in the confirmation prompt~

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
