### ISSUE TITLE
cptIMSCobraExport - remove ReDim Preserve in two places

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#315]
## Problem:
Formerly we were getting a blank "last element" of the array of custom fields, so we hacked off the last element with:

```vba
ReDim Preserve vArray(UBound(vArray)-1) 'v3.3.9
```

## Solution:
For whatever reason, this isn't working right--and it's actually hacking off the last non-zero-length element. Either:
- [x] Remove/Comment out the ReDim Preserve statement; or
- [x] Test for a blank value in the last element and _then_ ReDim Preserve

This was MY FAULT: bug introduced with the new cptQuickSort function.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
