### ISSUE TITLE
cptDynamicFilter - optionally show/hide Inactive Tasks

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#318]
## Request:

- [x] allow users to optionally show/hide Inactive tasks
- [x] defaults to true if no saved setting
- [x] enabled only when Application.Edition = `pjEditionProfessional`
- [x] toggle triggers refresh
- [x] include theme switch for geekMode
- [x] include in `cptGoRegex`

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
