### ISSUE TITLE
cptSetup_bas - minor cleanup needed on cptSetup()

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#32]
## Problem
In the `cptSetup()` subroutine:
- [x] Revise the prompt (no longer commenting out the ThisProject code);
- [x] allow user to cancel
- [x] Forgot to set `Application.StatusBar = ""` on exit

## Solution
do the things above

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch
