### ISSUE TITLE
DECM v6.0.0

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#325]
## Enhancement:
- [x] any updates from v5.0.0
- [x] any new metrics for v6.0.0?

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Issue #325 incorporated into Issue #356.
