### ISSUE TITLE
Request: cptAdjustment - enable Costs

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#329]
## Request:
User can select one or more tasks and set a _Target Remaining Cost_.
- [x] reject completed tasks
- [x] account for all `ResourceTypes`
- [x] account for `CostRateTables` (rates & escalations)
- [x] reject Resources where `AccrueAt <> pjProrated` (3) (if `pjStart` then costs already accrued; if `pjEnd` then interferes with Actual Work already accrued).
- [x] account for `CostPerUse` (Unstarted tasks only; `CostPerUse` is determined by Assignment Start)
- [ ] ~account for Overtime Work/Cost~ _this does not behave as expected*_
- [x] incorporate into `cptAdjustment_bas` and `cptAdjustment_frm`
- [x] account for `TaskType` - user can override (Remaining Duration: Retain; Adjust; Trust)

<details><summary>* Details on Overtime</summary>
<ul>
<li>adding overtime hours (task sheet only) respreads the allocation of regular work in a weird way</li>
<li>overtime hours are somewhat front-loaded, no rhyme or reason - no matter what contour is selected</li>
<li>when overtime hours (task sheet only) are removed, regular work is not redistributed as expected</li>
<li>unit allocations are adjusted upwards when overtime is added; when overtime is removed the allocation % is retained and regular work is not leveled</li>
<li>manual updates to the regular work after removing overtime work do not consistently update the peak units calc</li>
</ul>
</details> 

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
sent to user for testing. it works, but is _excruciatingly_ slow. need to optimize somehow.

**Comment by AronGahagan** [comment]
Using `DoEvents` after each `oTSV.Value` update instead of recalculating seems to be 1) accurate and 2) a bit faster. Added a progress bar so user doesn't think MS Project is just hanging, may alleviate some impatience.

**Comment by AronGahagan** [comment]
...moving form control updates (progress) and `DoEvents` after each `oAssignment` update also seems to be 1) accurate and 2) _even faster_...

**Comment by AronGahagan** [comment]
Speed seems best attainable. Now for better accuracy.
Last timescaledvalue should be very accurate "should be" total minus sum of timescalevalues-so-far.
