### ISSUE TITLE
Request: strip and sanitize

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#331]
## Requirements:

- [ ] prompt to `SaveAs` prior to running
- [ ] capture current durations/dates
- [ ] strip resource rates, costs, fixed costs, baseline0-10 costs (including timephased)
- [ ] option for `quick` vs `deep` clean
- [ ] optionally strip units from `Resource.Type = pjMaterial`
- [ ] optionally strip work, baseline0-10 work (including timephased)
- [ ] optionally strip budget, baseline0-10 budgets (including timephased)
- [ ] optionally delete resources
- [ ] restore durations/dates
- [ ] optionally delete all views (except submittal view)
- [ ] optionally delete custom file properties

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch
