### ISSUE TITLE
cptStatusSheet - optionally ignore assignments

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#332]
## Request:
Optionally allow user to skip assignments export
- [x] do not export assignments
- [x] perhaps capture settings used to create the sheet in a hidden worksheet
- [x] handle issues with importing this kind of worksheet

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
