### ISSUE TITLE
cptStatusSheet - pre-format Revised EV% as Percentage

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#335]
## Problem:
Not so much a glitch as an annoying inefficiency, but currently the user has to manually type in the `%` if the existing value is 0.

## Solution:
- [ ] pre-format the entry cell as `Percentage`
- [ ] include the `%` sign on the value, whatever it may be

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
already implemented - user must have been on earlier release
