### ISSUE TITLE
cptCore - office installation not found but references are set

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#340]
## Problem:
- User reports the "Office installation is not found" error upon opening MS Project.
- Microsoft Office path in the `Environ("PATH")` did not contain `EXCEL.EXE`
- BUT there is a reference to EXCEL.EXE already set, and the path is `C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE` -- which did not actually exist (or the user was not able to see it somehow)

...how can it be there (a reference is set) but also NOT be there (nothing returned by Dir())?

## Solution:
- [ ] try to find the path to Office Apps only if reference is not already set - `cptSetReferences` should only fire on initial install
- [ ] create function `cptGetOfficeDir` to avoid running same code for each Office App

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
