### ISSUE TITLE
Allow Multiple Configurations

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#343]
## Request:

- [ ] user can save different sets of config/settings
- [ ] user can export/import config/settings

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
I think this will have to be a Document Property. The Integration form will need a drop-down with all saved configurations. There could be a 'default' if the user only has one project, or has multiple projects with the same field mappings. A 'Save As' button that defaults to [program-acronym] as the name of the configuration, plus a binary field containing the actual cpt-settings.ini for that configuration. An option to 'copy' a configuration. Then nothing else in the code needs to be modified. The cptGetSetting and cptSaveSetting would read/write to the ADODB by default to keep current configuration changes in sync.

**Comment by AronGahagan** [comment]
- [ ] cannot overwrite `\settings\cpt-export-resource-userfields.adtg` -- add program/config column and overwrite the record only
