### ISSUE TITLE
cptDECM - multiple

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#356]
## Problems:
1. When user has Metrics settings but not Integration settings, cannot set cboLOE because it has not been populated yet
2. 1 CA: 1 CAM expects Unique ID
3. 1 WP: 1 EVT expects Unique ID 
4. EVT vs Milestone EVT on >1 fiscal period
5. What does "WPs with budgets" mean - didn't you change that to "w/o"?
6. analyze EVTs pulls from old Metrics settings not DECM mapping; make clear that old settings are WP-level, and identify what the 'CustomFields' option is used for
7. allow analyze EVTs to run against either "EVT" or "Milestone EVT"

## Solutions:
- [x] 1. comment out the earlier line of code that tries to set the value, it happens later anyway
- [x] 2. get user-selected field for CA and change from "contains" to "equals"
- [x] 3. get user-selected field for WPCN/WP and change from "contains" to "equals"
- [x] 4. maybe allow a Milestone EVT setting and use that as well as checking for a WP 0/100 w/ fiscal periods > 1
- [x] 5. change the name
- [x] 6. consolidate the mapping; make it feature-specific for what's required _for that metric_ in the ValidMap dialog
- [x] 7. add option for which to use (or include both?)

## Also:

- [x] upgrade to v6.0
- [x] pick list values on frmIntegration should all be alphabetized by CustomFieldName

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch

**Comment by AronGahagan** [comment]
tested on QuadCopter Master/Sub.
fixes needed:
- [ ] status percentage is wrong for master/sub
- [ ] cptDECM_bas:1660: if TaskHistory has less than 2 periods then cannot perform check
- [ ] 10A102a: limit analysis to PMB WP/Tasks
- [ ] 06A101a: wonky on paste (wp-ev.csv not found?)
- [ ] 06A204b: dangling logic is incorrect
- [ ] 06A211a: high float description: "high total float (> 44 days)"
- [ ] 06A212a: out of sequence gets 2 but in neither filter nor export
- [ ] 06A401a: critical path gets 2 results but in neither filter nor export
- [ ] 06A401a: note is unclear
- [ ] Export: "FreezePanes" fails
