### ISSUE TITLE
cptNetworkBrowser - handle external tasks in standalone

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#359]
## Problem:
External predecessors have an "x" appended to UID when project is opened standalone. Need to remove the x for oRecordset.AddNew but also indicate to user if the oLink is External.

```vba
Trace/cptNetworkBrowser_bas.bas:240:        .Column(1, .ListCount - 1) = lngLinkUID Mod 4194304 & IIf(oLink.From.ExternalTask, "x", "")
Trace/cptNetworkBrowser_bas.bas:302:        .Column(1, .ListCount - 1) = lngLinkUID Mod 4194304 & IIf(oLink.To.ExternalTask, "x", "")
```

### Also:
- [x] ensure all oSubProjects are loaded in cptShowPreds() for the sake of oSubMap
- [x] when only 1 pred, x is added and cptSortNetworkBrowserLinks is not called
- [x] instead of appending "x" to UID_S, prefix the task name with "<>"
- [ ] also fix UI on smaller screens: adjust font, font size, listbox sizes

## Solution:

```vba
Trace/cptNetworkBrowser_bas.bas:240:        .Column(1, .ListCount - 1) = lngLinkUID Mod 4194304
Trace/cptNetworkBrowser_bas.bas:302:        .Column(1, .ListCount - 1) = lngLinkUID Mod 4194304
```

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
