### ISSUE TITLE
cptStatusSheet - multiple tweaks

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#361]
## Problems:
- case sensitivity frustrates the user, especially when not indicated as such.
- directory doesn't exist on first run with both "Status Requests" _and_ chkAppendStatusDate
- QuickPart '' not found
- lboItems.Count = 0 not marked red when invalid

## Solutions:
- [x] make it case insensitive ~or at least notify the user~
- [x] iterate each level of user's chosen path and confirm existence
- [x] fix QuickPart '' not found
- [x] fix validation on lboItems.Count = 0

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
