### ISSUE TITLE
cptCore - deal with non-standard MS Office Path variables

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#366]
## Problem:
User's path has two Microsoft Office directories. User's path is `.../Microsoft Office/Client` but files needed live under `.../Microsoft Office/root/Client/Office16/` or something wacky like that.

## Solution:
- [x] get path containing "Microsoft Office"
- [x] start at top level
- [x] search through subfolders recursively until file(s) are found
- [x] return path
- [x] if no Microsoft Office in Environment Variable then return zero-length string

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
