### ISSUE TITLE
cptUpgrade_frm - review error logs from L3H KEO

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#375]
## Problems:

`cptUpgrades_frm.log: Line 2: The Form or MDIForm name cptUpgrades_frm is already in use; cannot load this form.`

`cptText_frm.log: Line 2: The Form or MDIForm name cptText_frm is already in use; cannot load this form.`

## Solutions:

- [x] ensure cptUpgrades_frm auto-upgrades prior to anything else
- [x] ensure cptUpgrades_frm is not listed in the ListBox
- [x] ensure other cpt forms are closed prior to upgrade attempt

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch

**Comment by AronGahagan** [comment]
[cptText_frm.log](https://github.com/AronGahagan/cpt-dev/files/14512156/cptText_frm.log)
[cptUpgrades_frm.log](https://github.com/AronGahagan/cpt-dev/files/14512157/cptUpgrades_frm.log)
