### ISSUE TITLE
installation - remove note about installing to non-cached Enterprise

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#376]
## Problem:
Users cannot install modules into the non-cached Enterprise Project Global -- they are met with a warning/error.

```vba
cptSetup_bas.bas-62-    strMsg = strMsg & "> Global.MPT" & vbCrLf
cptSetup_bas.bas:63:    strMsg = strMsg & "> Global (+ non-cached Enterprise) for testing purposes only" & vbCrLf
cptSetup_bas.bas-64-    strMsg = strMsg & "> Checked-out Enterprise Global (when ready to release to Enterprise user base)" & vbCrLf & vbCrLf
```

## Solution:
Remove that option from the pop-up.

```vba
cptSetup_bas.bas-62-    strMsg = strMsg & "> Global.MPT" & vbCrLf

cptSetup_bas.bas-64-    strMsg = strMsg & "> Checked-out Enterprise Global (when ready to release to Enterprise user base)" & vbCrLf & vbCrLf
```

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
- [ ] also change installation instructions: 1) drag over modules; 2) run "cptSetup"
- [ ] clarify upgrade instructions: 1) try OTA; 2) reinstall

**Comment by AronGahagan** [comment]
This is not an issue, it works as expected.
