### ISSUE TITLE
cptBackbone - option "also add task structure" not "taking"

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#379]
## Problem:
- [ ] option to 'also build task structure' seems to fire even if the box isn't checked
- [ ] should probably warn user before adding tasks to current file, recommend running in empty file then LCF over

## Solution:
do smarter things

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
Option to 'also create task structure' should be available in all import situations _except_ 'create from task structure.'
