### ISSUE TITLE
cptStatusSheetImport - SetSplitBar fails

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#380]
## Problems:

`SetSplitBar` fails if BottomPane is active. Check the following:

```vba
Core/cptCore_bas.bas:595:    SetSplitBar ShowColumns:=ActiveProject.TaskTables(ActiveProject.CurrentTable).TableFields.Count
Status/cptStatusSheetImport_bas.bas:1225:    SetSplitBar ShowColumns:=ActiveProject.TaskTables(ActiveProject.CurrentTable).TableFields.Count
Status/cptStatusSheetImport_bas.bas:1241:    SetSplitBar ShowColumns:=ActiveProject.TaskTables(ActiveProject.CurrentTable).TableFields.Count
Status/cptStatusSheetImport_bas.bas:1250:    SetSplitBar ShowColumns:=ActiveProject.TaskTables(ActiveProject.CurrentTable).TableFields.Count
Status/cptStatusSheet_bas.bas:590:  SetSplitBar ShowColumns:=ActiveProject.TaskTables(ActiveProject.CurrentTable).TableFields.Count
Status/cptStatusSheet_bas.bas:1233:  SetSplitBar ShowColumns:=ActiveProject.TaskTables(ActiveProject.CurrentTable).TableFields.Count
```

## Solution:
- [x] ensure `TopPane.Activate` happens prior to `SetSplitBar`

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
