### ISSUE TITLE
cptBackbone - fix-improve XLSX import

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#384]
## Problem:
- [x] header validation should not be case sensitive
- [x] logic for checking headers is wrong
- [x] dummy task should be at OutlineLevel 1

## Solution:
- [x] make header validation case insensitive
- [x] fix logic for checking headers
- [x] move dummy task to OutlineLevel 1

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
