### ISSUE TITLE
cptBackbone - allow "merge"

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#392]
## Enhancement:
Allow user to merge - meaning, revise descriptions on existing codes, add new levels

- [ ] capture existing code, level|description in Dictionary
- [ ] capture existing task data in UID|Code Dictionary
- [ ] update the picklist with modified descriptions
- [ ] restore task selections; kick out where new child levels have invalidated current setting; kick out list of tasks with no settings

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch
