### ISSUE TITLE
cptBackbone - fix a few minor issues

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#404]
## todo:
- [x] catch when `LEN([DESCRIPTION]) > 255`
- [x] catch when `[CODE]` is blank
- [x] use `MAX([LEVEL])` when building code mask

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
