### ISSUE TITLE
health metrics for non-EV schedules

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#408]
## Problem:
need some basic health metrics for non-EV schedules:
- [ ] missing preds
- [ ] missing succs
- [ ] out of sequence
- [ ] ...DCMA14?

## Solution:
find and restore old DCMA 14 metrics

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch
