### ISSUE TITLE
Request - Age Forecast Dates

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#41]
## Feature Request
Include a macro to automatically save X periods of forecast data in either the Interim Plan or Baseline field sets (prefer baseline).

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
Requirements:
- [ ] UserForm which allows user to select how many weeks to keep, and which fields to use, either Start / Finish or Baseline Start / Finish.
- [ ] Save settings between sessions.
- [ ] Set of filters / menu options to quickly show what has changed "since {date}"
- [ ] Track all history in `ActiveProject.ProjectNotes` -- or in an adtg file? ...produce trend charts?
