### ISSUE TITLE
Request: improve cptText_bas.cptFindDuplicateTaskNames() for master/sub

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#410]
## Enhancements:
- [x] if master/sub, then ensure subprojects are loaded/expanded
- [x] maybe adodb or an array would be faster; give results in a dialog for immediate correction
- [x] _optionally_ export to Excel

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
