### ISSUE TITLE
properly instantiate UserForms

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#411]
## Problems:
1. Evidently I have not been properly instantiating UserForms; working directly on the _class_ instead of with an _instance_. e.g.,

```vba
With cptStatusSheet_frm
...
End With
```
2. Modeless UserForms are not properly hidden/unloaded.
3. Modal UserForms are not properly hidden/unloaded.
4. UserForms are not always properly unloaded from memory.
5. `QueryClose` is unused.

## Solutions:
- [x] 1. Properly instantiate.
```vba
Set myStatusSheet_frm = New cptStatusSheet_frm
With myStatusSheet_frm
...
End With
```
- [x] 2. With (`[UserForm].Show 0 '0 = False = VBA.FormShowConstants.vbModeless`): use `Me.Hide` within form's code; use `Unload Me` in `UserForm_Terminate` Event.
- [x] 3. With (`[UserForm].Show 1 '1 = True = VBA.FormShowConstants.vbModal`): use `Me.Hide` within form's code; use `Unload` from the calling module.
- [x] 4. In both instances, the UserForm should be cleared from memory (`Set [UserForm] = Nothing`) unless the calling subroutine needs it again (hint: if the subroutine has a `(ByRef [myUserForm] As [cptUserForm])` variable, then do not kill it).
- [x] 5. `If CloseMode = vbQueryClose.vbFormControlMenu Then / Me.Hide / Cancel = True / End IF`

## UserForms subject to this change:
- [x] cptAbout_frm
- [x] cptAdjustment_frm
- [x] cptAgeDates_frm
- [x] cptBackbone_frm
- [x] cptCalendarExceptions_frm
- [x] cptCostRateTables_frm
- [x] cptDataDictionary_frm
- [x] cptDECM_frm
- [x] cptDECMTargetUID_frm
- [x] cptDynamicFilter_frm
- [x] cptFilterByClipboard_frm
- [x] cptFiscal_frm
- [x] cptIntegration_frm
- [x] cptMetricsData_frm
- [x] cptNetworkBrowser_frm
- [x] cptQBD_frm `pre-release`
- [x] cptResetAll_frm
- [x] cptResourceDemand_frm
- [x] cptSaveLocal_frm
- [x] cptSaveMarked_frm
- [x] cptSettings_frm
- [x] cptSmartDuration_frm
- [x] cptStatusSheet_frm
- [x] cptStatusSheetImport_frm
- [x] cptTaskHistory_frm
- [x] cptText_frm
- [x] cptUpgrades_frm

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
