### ISSUE TITLE
only query cptErrorTrapping once per routine

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#415]
## Problem:

1. The idiot who coded this crap keeps pinging the cptErrorTrapping function which will not change over the course of running a subroutine. 
2. Same goes for cptDir.

## Solution:
1. Set `blnErrorTrapping = cptErrorTrapping` once at the start and just use _that_. 
2. Set 'strCptDir = cptDir` once at the start and just use _that_.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Files to review for `cptErrorTrapping`:
- [ ] Admin/cptAdmin_bas.bas
- [ ] Backbone/cptBackbone_bas.bas
- [ ] Backbone/cptBackbone_frm.frm
- [ ] Calendar/cptCalendarExceptions_bas.bas
- [ ] Calendar/cptFiscal_bas.bas
- [ ] Calendar/cptFiscal_frm.frm
- [ ] Core/cptAbout_frm.frm
- [ ] Core/cptCore_bas.bas
- [ ] Core/cptResetAll_frm.frm
- [ ] Core/cptSettings_frm.frm
- [ ] CostRateTables/cptCostRateTables_bas.bas
- [ ] Count/cptCountTasks_bas.bas
- [ ] CustomFields/cptDataDictionary_bas.bas
- [ ] CustomFields/cptDataDictionary_frm.frm
- [ ] CustomFields/cptSaveLocal_bas.bas
- [ ] CustomFields/cptSaveLocal_frm.frm
- [ ] Integration/cptAdjustment_bas.bas
- [ ] Integration/cptAdjustment_frm.frm
- [ ] Integration/cptIntegration_frm.frm
- [ ] Metrics/cptDECMTargetUID_frm.frm
- [ ] Metrics/cptDECM_bas.bas
- [ ] Metrics/cptDECM_frm.frm
- [ ] Metrics/cptMetricsData_frm.frm
- [ ] Metrics/cptMetrics_bas.bas
- [ ] ResourceDemand/cptResourceDemand_bas.bas
- [ ] ResourceDemand/cptResourceDemand_frm.frm
- [ ] Status/cptAgeDates_bas.bas
- [ ] Status/cptAgeDates_frm.frm
- [ ] Status/cptSmartDuration_bas.bas
- [ ] Status/cptStatusSheetImport_bas.bas
- [ ] Status/cptStatusSheetImport_frm.frm
- [ ] Status/cptStatusSheet_bas.bas
- [ ] Status/cptStatusSheet_frm.frm
- [ ] Status/cptTaskHistory_bas.bas
- [ ] Status/cptTaskHistory_frm.frm
- [ ] Text/cptDynamicFilter_bas.bas
- [ ] Text/cptDynamicFilter_frm.frm
- [ ] Text/cptFilterByClipboard_bas.bas
- [ ] Text/cptFilterByClipboard_frm.frm
- [ ] Text/cptText_bas.bas
- [ ] Text/cptText_frm.frm
- [ ] Trace/cptCriticalPathTools_bas.bas
- [ ] Trace/cptNetworkBrowser_bas.bas
- [ ] Trace/cptNetworkBrowser_frm.frm
- [ ] Trace/cptSaveMarked_bas.bas
- [ ] Trace/cptSaveMarked_frm.frm
- [ ] cptPatch_bas.bas

Files to review for `cptDir`:
- [ ] Admin/cptAdmin_bas.bas
- [ ] Backbone/cptBackbone_bas.bas
- [ ] Core/cptCore_bas.bas
- [ ] Core/cptSettings_frm.frm
- [ ] Core/cptUpgrades_frm.frm
- [ ] CustomFields/cptDataDictionary_bas.bas
- [ ] CustomFields/cptDataDictionary_frm.frm
- [ ] CustomFields/cptSaveLocal_bas.bas
- [ ] CustomFields/cptSaveLocal_frm.frm
- [ ] Metrics/cptDECM_bas.bas
- [ ] Metrics/cptMetricsData_frm.frm
- [ ] Metrics/cptMetrics_bas.bas
- [ ] ResourceDemand/cptResourceDemand_bas.bas
- [ ] Status/cptStatusSheetImport_bas.bas
- [ ] Status/cptStatusSheet_bas.bas
- [ ] Status/cptStatusSheet_frm.frm
- [ ] Status/cptTaskHistory_bas.bas
- [ ] Status/cptTaskHistory_frm.frm
- [ ] Trace/cptSaveMarked_bas.bas
- [ ] Trace/cptSaveMarked_frm.frm
- [ ] cptSetup_bas.bas
