### ISSUE TITLE
cptSaveLocal_bas - few tweaks for use on a very large project

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#416]
## Problems:
1. Need to ensure SummaryTasks are visible every time you try to OutlineShowAllTasks.
2. Needs a progress/status bar for very large projects.
3. Needs cptSpeed in the cptSaveDown loop.
4. The ribbon button should only appear if the user is connected (and working online)?

## Solutions:
do it

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout appropriate branch and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `Issue #XXX - `
- [ ] merge `topic` into appropriate branch(es) and push
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
- [ ] add button to `Delete Map` and (optionally) delete the LCF and (optionally) delete the task data
- [ ] enable double-click on lboECF to Map/Unmap

**Comment by AronGahagan** [comment]
- [ ] if ActiveProject.Subprojects.count>0 then open all of them, not read only, on form open
- [ ] merge LCF analysis and 'Take It' into this one form
- [ ] show current list of mapped fields separately - waste of space to duplicate in both listboxes
