### ISSUE TITLE
move cptQuickSort() from cptIMSCobraExport_bas to cptCore_bas; keep/rename in former and make it private

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#418]
## Problem:
There are calls to cptQuickSort() in cptCore_bas but cptQuickSort() lives in cptIMSCobraExport_bas, which is not (always) loaded in the bootstrap step. Compiling fails.

## Solution:
- [x] copy cptQuickSort() from cptIMSCobraExport_bas to cptCore_bas, keep it a Public Function
- [x] rename cptQuickSort() in cptIMSCobraExport_bas to QuickSort() and make it a Private Function

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout appropriate branch and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `Issue #XXX - `
- [x] merge `topic` into appropriate branch(es) and push
- [x] delete topic branch
