### ISSUE TITLE
Feature Request: Optionally Include Labor Rates on Resource Demand Export

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#42]
## Request
Optionally include labor rate sets on resource demand export. Include rate, include cost.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
todo:
- [x] update form to include optional export of baseline
- [x] update form to include checkboxes for which rate sets to include
- [x] if cost rate tables are exported then also export current assignment cost rate table along with selected items
- [x] include cost rate table worksheet for reference
- [ ] update settings i/o

**Comment by AronGahagan** [comment]
Ready for testing.

**Comment by AronGahagan** [comment]
Vulnerability: if an error stops the process after an Assignment Cost Rate Table has been changed but before it gets reset to its original state the file could be left in an unintended state and cause incorrect calculations.
- [ ] Option 1: warn the user of the above;
- [ ] Option 2: capture current assignment settings and restore on error

**Comment by AronGahagan** [comment]
Released to test.
