### ISSUE TITLE
cptStatusSheet - user can create multiple workbooks/sheets and limit by multiple field items

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#50]
## Feature Request
When creating a Status Sheet, the user can optionally create a single status workbook, a workbook with multiple worksheets (based on one or many values in a given field), or multiple workbooks (based on one or many values in a given field). 

Use cases:
- create a status sheet for only *this* CAM;
- create a status sheet for only *that* leg of the CWBS;
- create a status sheet for only *the other* WPCN.

## Notes:
- [x] ensure 'for each' field is included in export list
- [x] when importing saved export fields, prompt to remove any whose name has changed
- [x] for filtered worksheets, include related summaries (but not all summaries)

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
Created branch `Issue40-statusSheetEnhancements`.

### Strategy:
- [ ] Create 'Single Workbook'
- [ ] If 'Worksheet for each' or 'Workbook for each':
  - [ ] save single workbook as original
  - [ ] for each field item, copy the worksheet and then filter out where [cboEach]<>[lboItem] (use UID in case 'for each' field is not included in export list
  - [ ] if workbook then save new worksheet as its own workbook

**Comment by AronGahagan** [comment]
User should also be able to create a single workbook limited by certain custom field items.

**Comment by AronGahagan** [comment]
- [ ] User's Group should persist to status sheet(s) instead of only relying on native summary tasks.

**Comment by AronGahagan** [comment]
- [ ] Fix incorrect filename on certain combinations of settings.

**Comment by AronGahagan** [comment]
Release to test.
