### ISSUE TITLE
Globally add Optional 'Erl' to all calls to cptHandleErr()

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#51]
## Request
Globally add optional `Erl` to all calls to `cptHandleErr`. If line numbers are enabled, the error message will include the Erl (**E**rror **r**eference **l**ine?). If there is no error, then Erl returns `0` and the sub `cptHandleErr()` will ignore it.

## Suggestion
```visual-basic
- Call cptHandleErr("cptText_bas", "cptResetRowHeight", err)
+ Call cptHandleErr("cptText_bas", "cptResetRowHeight", err, Erl)
```

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Bash/git/grep/sed...incredible. Did this for all *.bas, *frm, and *.cls files in both the root and all subdirectories with a *single line of code*:

` git grep -l err\) | xargs sed -i 's/err)/err, Erl)/g'`

HT: https://blog.jasonmeridth.com/posts/use-git-grep-to-replace-strings-in-files-in-your-git-repository/

todo:
- [ ] bump all patches
- [ ] bump all versions in `CurrentVersions.xml`

**Comment by AronGahagan** [comment]
When merging, be sure to ignore whitespace errors (sed created one on every line):

`git merge -Xignore-space-change`

HT: https://stackoverflow.com/questions/9776527/merging-without-whitespace-conflicts

**Comment by AronGahagan** [comment]
Celebrated too soon. Evidently running `sed` with the `-i` switch (edit inline) messed with the `LF` vs. `CRLF` (or something) in the UserForm modules, and VBA no longer recognizes them as forms, tripping an error. Continuing testing.

**Comment by AronGahagan** [comment]
Tried running `git add --renormalize`. When using File > Import... from the VBE it appears to work; but running cptUpgrades_frm does not. Used File > Import to pull in the issue51-addErl branch, and the VBE recognized them fine. Then ran my gitVBA export tool, assuming that because VBE recognized them something was 'fixed.' All modules were modified. Then committed and pushed. Then tried to re-run the Upgrades and they still were not recognized.

**Comment by AronGahagan** [comment]
Everything was fine until I ran the `sed -i` operation which likely changed line endings. When I added those modified files, I got the CRLF to LF warnings since I have `core.autocrlf true`. Maybe if I start over from the beginning and set `core.autocrlf false` it will work.

FMI: https://lostechies.com/keithdahlby/2011/04/06/windows-git-tip-hide-carriage-return-in-diff/

**Comment by AronGahagan** [comment]
Confirmed: `sed -i` actually creates a new file and then renames it after the operation completes; which means the Windows line feeds `CR+LF` are replaced with something unrecognizable by the VBE.

Instead will try `perl -pi -e 's/err\)/err, Erl\)/g'` and run it against `*.bas, *.cls, *.frm */*.bas, */*.frm, */*.cls`. Running it with `core.autocrlf false`. This edits the original file unlike `sed -i`, and keeps `CRLF` unchanged.

...success. All versions bumped and ready to merge into `master`. 

Holding off on merge/push into master until I'm not travelling in case there's a problem.
