### ISSUE TITLE
cptText_bas: cptFindDuplicateTaskNames() - 438: Object doesn't support property or method

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#56]
## Problem
User EK reports the following error when attempting to run the Duplicate Task Name check:

![image](https://user-images.githubusercontent.com/38786138/61310290-fd32c380-a7c1-11e9-8c3f-023fe8c5bac3.png)

I have not yet been able to reproduce this error.

## Solution
TBD.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
Closing this issue as stale; it has been a year and I have heard no other complaints, and have not been able to reproduce the error.
