### ISSUE TITLE
Network Browser

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#57]
## Request:
Upgrade and incorporate the Network Browser.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
- [ ] make compatible with master/subs
- [ ] add branding
- [ ] make display of Network Browser optional
- [ ] include on ribbon mark/unmark/saved marks (by GUID, Title, Description, details)

**Comment by AronGahagan** [comment]
[ ] - navigate back/fwd using UID instead of ID
