### ISSUE TITLE
cptStatusSheet_bas - legend formats not applied as expected

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#58]
## Problem:
In the module Formats in the legend are not being applied as expected leading to user confusion.

## Solution:
Apply the formats.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Aligned legend with conditional formats and tweaked conditional format formulae. Released for user testing.

**Comment by AronGahagan** [comment]
User's default date format in MS Project was DDD M/D/YY which translated into Excel as text, so conditional formatting wasn't getting triggered. Updated `basStatusSheet_bas` to capture user's default date format, change it to mm/dd/yy and then reset before exiting. Works on my end; released to user for testing.

**Comment by AronGahagan** [comment]
Couple more knickknacks:
- [ ] _EV%_ shoud be in % format
- [ ] _New EV%_ should be in % format
- [ ] _New ETC_ conditional formatting should match _EV%_ conditional formatting, and should be at both Task and Assignment levels.
- [ ] Task-Level _Revised ETC_ should be a formula...which means _Revised ETC_ should be added when the Task is being processed instead of after the fact.

**Comment by AronGahagan** [comment]
Conditional formatting on the _Revised ETC_ column are extremely slow. Consider:
- [ ] Add all headers first
- [ ] grab existing values as placeholders (new ev%, new etc)
- [ ] for assignments grab dates and evp but hide them (font = white)
- [ ] bulk apply _Revised ETC_ conditional formats as is done with Task rows

**Comment by AronGahagan** [comment]
User DB reports that after updating his date formatting everything appears to be working correctly. Will work on speed improvements then release this hotfix to the masses.

**Comment by AronGahagan** [comment]
released
