### ISSUE TITLE
Speed Up the Status Sheet

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#60]
## Problem:
Creation of the status sheet(s) is too slow; in particular, the application of conditional formatting. 

## Solution
Not sure -- figure something out.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Conditional formatting on the _Revised ETC_ column is extremely slow. Consider:
- [ ] Add all headers first
- [ ] grab existing values as placeholders (new ev%, new etc)
- [ ] for assignments grab dates and evp but hide them (font = white)
- [ ] bulk apply _Revised ETC_ conditional formats as is done with Task rows

**Comment by AronGahagan** [comment]
ADODB is far faster than writing to the sheet line by line. Maybe write all in-scope tasks to an ADODB.Recordset then dump to sheet before formatting it. Use Boolean flags for Summary, Milestone, Normal, and Assignment Rows. By far the slowest part is the conditional formatting. Maybe fill down task dates to assignments and bulk apply the formats?

**Comment by AronGahagan** [comment]
Included in #162
