### ISSUE TITLE
cptSetup - ensure ThisProject is set to ProjectGlobal

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#61]
## Problem:
Some users report that the toolbar is installed to the ActiveProject when `cptSetup()` is executed. Ensure installation is made to the `ProjectGlobal` instead.

## Solution:
Every instance of `ThisProject` in `cptSetup()` should be changed to `ProjectGlobal.ThisProject`.
- [ ] cptSetup_bas.bas
- [ ] Admin/cptAdmin_bas.bas
- [ ] Core/cptCore_bas.bas
- [ ] Core/cptUpgrades_frm.frm

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
Above solution is unnecessary, and unstable (user may rename his Global.MPT to be something _other than_ `ProjectGlobal`). 

This issue only manifests when the user does not `RTFM` and installs the `cptSetup_bas` module to a project file instead of to his Global.MPT. Added a prompt to exit setup if the user has not installed to his Global.MPT. Issue closed.
