### ISSUE TITLE
cptStatusSheet - ignore EVT when EV Tool is 'None'

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#64]
## Problem
From RB: "When selecting <none> as the cost tool, the user is still required to provide an EVT field map. When working certain programs, EV may not be required and an EVT field may not exist."

## Solution
- [x] only require EVT if Cost Tool <> None in `cptStatusSheet_frm.frm`
- [x] do not include EVT in column list in `cptStatusSheet_bas.bas`
- [x] skip conditional formatting for EVT checks in `cptStatusSheet_bas.bas`

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch
