### ISSUE TITLE
User can import status worksheet(s) to temporary fields

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#65]
## Feature Request:
User can select one or more workbooks (or a folder) and import updates to temporary fields.

- [x] drag-and-drop folder/file(s) selection
- [x] validate each file
- [ ] validate each entry - output if missing update
- [x] allow user to decide where to pull in the updates: AS, AF, FS, FF, EV%, Assignment ETC, 
   - [x] AS/AF to native fields or to custom field
   - [x] FS/FS to custom field
   - [x] EV% to 'New EV%'
   - [x] ETC to Assignment-level 'New ETC'
   - [x] Append comments (optional top/bottom) with date to Task Notes
- [ ] built-in filters to compare - on form
- [x] save/restore GUID-unique user settings

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Advanced features:
- [ ] "score" the updates - how many needed updates are missing? %
  - [ ] auto-generate an email with details
- [ ] double-click to open the source file
- [ ] Preview / What-if scenarios
- [ ] status request score? timely and accurate
   - [ ] GUID,StatusDate,CAM,Sent,Received - trend
   - [ ] timely: 0(none); 50(late); 100(on time); 120(early)
   - [ ] timely/2 + accuracy/2 = score (out of 100)

**Comment by AronGahagan** [comment]
More to do:
- [ ] mimic status sheet export with live view updates (task sheet)
- [ ] also create matching Task Usage view to match Import View
- [ ] also create filters to zero-in on changes
- [ ] prompt to apply views after import
- [ ] need some kind of delinquency report...

**Comment by AronGahagan** [comment]
release as-is
