### ISSUE TITLE
User can integrate fiscal calendar

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#66]
## Request:
User can upload and maintain a fiscal calendar.

## Requirements:
- [ ] Import from Excel or CSV
- [ ] Import MPM export file directly
- [ ] Import COBRA export file directly
- [ ] user can view / edit / export current settings
- [ ] not project-specific
- [ ] save as `cpt-fiscal.adtg`
- [ ] user can analyze EVTs (MPM or COBRA)
   - [ ] user identifies EVT field
   - [ ] user receives listbox with errors/suggestions
   - [ ] clicking on listbox item jumps to the task
- [ ] include fiscal in resource demand export

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch
