### ISSUE TITLE
Feature Request: SRA WAG

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#68]
## Request:
- [ ] User can select a target task and get a WAG SRA date based on some combinations of the following:
   - [ ] PERT date using three-point estimates (required by the DI-MGMT-81861B anyway).
   - [ ] get a run rate (adjusted for nearness to critical path, some how) and discrete only, on completed tasks to date and use that to project into the future. Use standard deviation of past tasks as PERT values.
- [ ] required inputs: either 30% discrete task completion OR three-point inputs
- [ ] create charts showing output

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
Resources:
- https://www.drdawnwright.com/easy-excel-inverse-triangular-distribution-for-monte-carlo-simulations/
- https://sourceforge.net/p/montecarloprj/code/HEAD/tree/trunk/src/

**Comment by AronGahagan** [comment]
- [ ] save/restore settings to `/cpt-backup/cpt-settings/cpt-quickMonte-settings.adtg`
