### ISSUE TITLE
cptResourceDemand - catch error when custom field is empty

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#82]
## Problem:
When custom field is empty an error is tripped...

## Solution:
Catch and release.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
I am not able to reproduce this error. Closing the issue, but will reopen if issue reappears.
