### ISSUE TITLE
Request: Stored Setting - Disable Updates

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#85]
## Request:
User requests the ability to disable updates/upgrades.

- [x] Create cptSettings_frm and cptSettings_bas
- [x] Update cptCore_bas to read settings file before showing cptUpgrades_frm
- [x] Update cptSettings.bas.cptBuildRibbonTab to include settings button
- [x] Update cptAdmin to correctly file cptSettings* files

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch
