### ISSUE TITLE
Request: Save ECFs to Local Custom Fields

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#90]
## Request:
Provide user with ability to save down field attributes and task field values from ECFs to local custom fields.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [x] delete topic branch

**Comment by AronGahagan** [comment]
Create an AutoMap feature!

**Comment by AronGahagan** [comment]
- [ ] Import saved mapping (by project GUID)
- [ ] Update table as user selects fields
- [ ] Provide filter for discrepancies
- [ ] AutoMap
- [ ] add the standard header [maybe make it more subtle on all forms for next release]

**Comment by AronGahagan** [comment]
- [ ] add button to ribbon, you dope
