### ISSUE TITLE
cptResourceDemand - add FTE and FTE_BL

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#91]
## Request:
Add FTE and FTE_BL to chart.

## Todo:
- [x] assign this issue
- [x] label the issue for enhancement or bug
- [x] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [x] checkout `develop` and create `topic` branch
- [x] design, code and test
- [x] update codemodule <cpt_version>x.y.z</cpt_version>
- [x] reset BLN\_TRAP\_ERRORS
- [x] update CurrentVersions.xml **manually**
- [x] commit changes prefix comment with `issueXX`
- [x] merge `topic` into `develop` and push
- [x] if hotfix: merge `develop` into `master` and push
- [x] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
- [ ] FTE_WEEK 
- [ ] Point FTE_WEEK to holiday exceptions
- [ ] FTE_MONTH
- [ ] Point FTE_MONTH ho holiday exceptions
- [ ] Include User Note to use FTE_MONTH if grouping by month
- [ ] Export Holidays/Exceptions from Project Calendar
- [ ] Setup a Fiscal Month Lookup: WE,YEARMO,HOURS
- [ ] Add Option on Worksheet to point FTE_MONTH to FISCAL; Indicate "CALENDAR MONTHS" vs "FISCAL PERIODS" on Table and Chart
- [ ] Add Conditional Formatting to Table

**Comment by AronGahagan** [comment]
- [ ] Include FTE_BL_WEEK
- [ ] Include FTE_BL_MONTH
