### ISSUE TITLE
Request: Upgrade Schedule Metrics

### ISSUE THREAD

**Issue by AronGahagan** [AronGahagan/cpt-dev#93]
## Request:
Include certain filter criteria to the Schedule QuickMetrics. Move to a dialog. Add other metrics.

![image](https://user-images.githubusercontent.com/38786138/75181403-1ca4ae00-570c-11ea-83d3-b77345b6bfb3.png)

## Todo:
- [ ] assign this issue
- [ ] label the issue for enhancement or bug
- [ ] label the issue with codemodule (so fixes can be aggregated and hotfixed together)
- [ ] checkout `develop` and create `topic` branch
- [ ] design, code and test
- [ ] update codemodule <cpt_version>x.y.z</cpt_version>
- [ ] reset BLN\_TRAP\_ERRORS
- [ ] update CurrentVersions.xml **manually**
- [ ] commit changes prefix comment with `issueXX`
- [ ] merge `topic` into `develop` and push
- [ ] if hotfix: merge `develop` into `master` and push
- [ ] if feature: wait for release, do **not** merge into master
- [ ] delete topic branch

**Comment by AronGahagan** [comment]
Include the following:

## General
- [ ] Task Counters

## Schedule Metrics
- [ ] Late Starts/Finishes with S-chart
- [ ] SPI (trend)
- [ ] BEI (trend)
- [ ] CPLI (trend)
- [ ] CEI (trend)
- [ ] TFCI (trend) `< maybe not`
- [ ] Earned Schedule

## Staffing Metrics
- [x] Staffing Profile
- [ ] Previous period ETC vs. previous period timecards

## Risks and Opportunity Metrics
- [ ] Schedule Margin Burndown Chart(s)
